app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

admin_team:
    resource: "@TeamBundle/Resources/config/routing.yml"
    prefix:   /admin/team

admin_fairplay:
    resource: "@InfoBundle/Resources/config/fairplay/routing.yml"
    prefix:   /admin/fairplay

admin_history:
    resource: "@InfoBundle/Resources/config/history/routing.yml"
    prefix:   /admin/history



