info:
    resource: "@InfoBundle/Resources/config/routing.yml"
    prefix:   /admin

app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

team:
    resource: "@TeamBundle/Resources/config/routing.yml"
    prefix:   /admin/team
