app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

team:
    resource: "@TeamBundle/Resources/config/routing.yml"
    prefix:   /admin/team

planning:
    resource: "@PlanningBundle/Resources/config/routing.yml"
    prefix:   /admin/planning