app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

admin_team:
    resource: "@TeamBundle/Resources/config/routing.yml"
    prefix:   /admin/team

planning:
    resource: "@PlanningBundle/Controller/"
    type:     annotation
    prefix:   /planning
admin_fairplay:
    resource: "@InfoBundle/Resources/config/fairplay/routing.yml"
    prefix:   /admin/fairplay

admin_history:
    resource: "@InfoBundle/Resources/config/history/routing.yml"
    prefix:   /admin/history



admin_planning_event:
    resource: "@PlanningBundle/Resources/config/event/routing.yml"
    prefix:   /admin/planning/event

admin_planning_date:
    resource: "@PlanningBundle/Resources/config/date/routing.yml"
    prefix:   /admin/planning/date

admin_planning_training:
    resource: "@PlanningBundle/Resources/config/training/routing.yml"
    prefix:   /admin/planning/training

admin_place:
    resource: "@PlaceBundle/Resources/config/routing.yml"
    prefix:   /admin/place
