# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    asptt.email.application_mailer:
        class: AppBundle\Services\ApplicationMailer
        arguments:
            - "@mailer"

    asptt.email.update_notifier:
          class: AppBundle\Services\UpdateNotifier
          arguments:
              - "@mailer"

    asptt.doctrine_listener.edito_update:
        class: InfoBundle\DoctrineListener\InfoCreationListener
        arguments:
            - "@asptt.email.update_notifier"
        tags:
            - { name: doctrine.event_listener, event: postUpdate }