# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    asptt.email.application_mailer:
        class: AppBundle\Services\ApplicationMailer
        arguments:
            - "@mailer"