admin_fairplay_index:
    path:     /
    defaults: { _controller: "InfoBundle:FairPlay:index" }
    methods:  GET

admin_fairplay_show:
    path:     /{id}/show
    defaults: { _controller: "InfoBundle:FairPlay:show" }
    methods:  GET

admin_fairplay_new:
    path:     /new
    defaults: { _controller: "InfoBundle:FairPlay:new" }
    methods:  [GET, POST]

admin_fairplay_edit:
    path:     /{id}/edit
    defaults: { _controller: "InfoBundle:FairPlay:edit" }
    methods:  [GET, POST]

admin_fairplay_delete:
    path:     /{id}/delete
    defaults: { _controller: "InfoBundle:FairPlay:delete" }
    methods:  DELETE
