<?php

namespace EventBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPostByTitle($title)
    {
        return $this
        ->createQueryBuilder('p')
        ->where('p.validated = 1')
        ->andWhere('p.title = :title')
        ->setParameter('title',$title)
        ->getQuery()
        ->getResult();
    }
    public function findThreeLastPosts()
    {
        return $this->createQueryBuilder('p')
            ->where('p.validated = 1')
            ->orderBy('p.publishedAt', 'DESC')
            ->getQuery()
            ->setMaxResults(3)
            ->getResult();
    }

    public function getPostsByCategory($idPostCategory)
    {
        return $this->createQueryBuilder('p')
            ->where('p.validated = 1')
            ->andWhere('p.postCategory = :id')
            ->setParameter('id', $idPostCategory)
            ->orderBy('p.publishedAt', 'DESC')
            ->getQuery()
            ->getResult();
    }

    public function getByResearch($search)
    {
        // Création du QueryBuilder pour rechercher un mot dans le contenu ou le titre des artiles
        return $this->createQueryBuilder('p')
            ->where('p.title LIKE :search')
            ->orWhere('p.content LIKE :search')
            ->andWhere('p.validated = 1')
            ->setParameter('search', '%' .$search. '%')
            ->getQuery()
            ->getResult();
    }

    public function findLastPostByCategory($idPostCategory)
    {
        return $this->createQueryBuilder('p')
            ->where('p.validated = 1')
            ->andWhere('p.postCategory = :id')
            ->setParameter('id', $idPostCategory)
            ->orderBy('p.publishedAt', 'DESC')
            ->getQuery()
            ->setMaxResults(1)
            ->getResult();
    }
 
}
