<?php

namespace EventBundle\Repository;

/**
 * SeoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeoRepository extends \Doctrine\ORM\EntityRepository
{
}
