<?php

namespace PlanningBundle\Repository;

/**
 * DateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DateEventRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllOrderedByDate()
    {
        return $this->createQueryBuilder('d')
            ->orderBy('d.date', 'ASC')
            ->getQuery()
            ->getResult();
    }
}
