<?php

namespace PlanningBundle\Repository;

/**
 * DayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DayRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllOrderedByDay()
    {
        return $this->createQueryBuilder('d')
            ->orderBy('d.id', 'ASC')
            ->getQuery()
            ->getResult();
    }
}
