<?php

namespace PlanningBundle\Repository;
use PlanningBundle\Entity\Event;
/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{
    public function getEventsByTeam($team)
    {
        return $this
            ->createQueryBuilder('e')
            ->where('e.team = :team')
            ->setParameter('team', $team)
            ->getQuery()
            ->getResult()
        ;
    }

}
