admin_user_index:
    path:     /
    defaults:
        _controller: UserBundle:User:index

admin_user_show:
    path:     /{id}/show
    defaults:
        _controller: UserBundle:User:show
    requirements:
        id: \d+

admin_user_new:
    path:     /new
    defaults:
        _controller: UserBundle:User:new

admin_user_edit:
    path:     /{id}/edit
    defaults:
        _controller: UserBundle:User:edit
    requirements:
            id: \d+

admin_user_delete:
    path:     /{id}/delete
    defaults:
        _controller: UserBundle:User:delete
    requirements:
            id: \d+