app_index:
    path:     /
    defaults:
        _controller: AppBundle:Default:index

team_view:
    path: /team/{slug}
    defaults:
        _controller: AppBundle:Team:view

planning_index:
    path: /planning
    defaults:
        _controller: AppBundle:Planning:index

planning_annual:
    path: /planning/annual
    defaults:
        _controller: AppBundle:Planning:annualPlanning

planning_weekend:
    path: /planning/week-end
    defaults:
        _controller: AppBundle:Planning:weekendPlanning
history_view:
    path: /history
    defaults:
        _controller: AppBundle:History:view

fairplay_view:
    path: /fairplays
    defaults:
        _controller: AppBundle:Fairplay:view
