app_index:
    path:     /
    defaults:
        _controller: AppBundle:Default:index

app_contact:
    path:     /contact
    defaults:
        _controller: AppBundle:Mail:contact

app_team_view:
    path: /team/{slug}
    defaults:
        _controller: AppBundle:Team:view

app_post_index:
    path: /post
    defaults:
        _controller: AppBundle:Post:index

app_post_view:
    path:     /post/{id}
    defaults:
        _controller: AppBundle:Post:view
    requirements:
        id: \d+

app_post_club:
    path: /post/club
    defaults:
        _controller: AppBundle:Post:showEventClub

app_post_handball:
    path: /post/handball
    defaults:
        _controller: AppBundle:Post:showEventHandball

app_planning_index:
    path: /planning
    defaults:
        _controller: AppBundle:Planning:index

app_planning_annual:
    path: /planning/annual
    defaults:
        _controller: AppBundle:Planning:annualPlanning

app_planning_weekend:
    path: /planning/week-end
    defaults:
        _controller: AppBundle:Planning:weekendPlanning

app_planning_training:
    path: /planning/training
    defaults:
        _controller: AppBundle:Planning:trainingPlanning

app_history_view:
    path: /histoire
    defaults:
        _controller: AppBundle:History:view

app_fairplay_view:
    path: /charte
    defaults:
        _controller: AppBundle:Fairplay:view

app_contact_list:
    path: /liste-contact
    defaults:
        _controller: AppBundle:ContactList:listContact

app_place_list:
    path: /liste-gymnase
    defaults:
        _controller: AppBundle:PlaceList:listPlace

admin_index:
    path:     /admin
    defaults:
        _controller: AppBundle:Admin:index
