app_index:
    path:     /
    defaults:
        _controller: AppBundle:Default:index

team_view:
    path: /team/{slug}
    defaults:
        _controller: AppBundle:Team:view

post_index:
    path: /post
    defaults:
        _controller: AppBundle:Post:index