app_index:
    path:     /
    defaults:
        _controller: AppBundle:Default:index

team_view:
    path: /team/{slug}
    defaults:
        _controller: AppBundle:Team:view

post_view:
    path: /post
    defaults:
        _controller: AppBundle:Post:index

post_detail:
    path:     /post/{id}
    defaults:
        _controller: AppBundle:Post:show
    requirements:
        id: \d+
