app_index:
    path:     /
    defaults:
        _controller: AppBundle:Default:index

app_contact:
    path:     /contact
    defaults:
        _controller: AppBundle:Mail:contact

admin_index:
    path:     /admin
    defaults:
        _controller: AppBundle:Admin:index

team_view:
    path: /team/{slug}
    defaults:
        _controller: AppBundle:Team:view

post_view:
    path: /post
    defaults:
        _controller: AppBundle:Post:index

post_detail:
    path:     /post/{id}
    defaults:
        _controller: AppBundle:Post:show
    requirements:
        id: \d+

post_club:
    path: /post/club
    defaults:
        _controller: AppBundle:Post:showEventClub

post_handball:
    path: /post/handball
    defaults:
        _controller: AppBundle:Post:showEventHandball
planning_index:
    path: /planning
    defaults:
        _controller: AppBundle:Planning:index

planning_annual:
    path: /planning/annual
    defaults:
        _controller: AppBundle:Planning:annualPlanning

planning_weekend:
    path: /planning/week-end
    defaults:
        _controller: AppBundle:Planning:weekendPlanning

planning_training:
    path: /planning/training
    defaults:
        _controller: AppBundle:Planning:trainingPlanning

history_view:
    path: /histoire
    defaults:
        _controller: AppBundle:History:view

fairplay_view:
    path: /charte
    defaults:
        _controller: AppBundle:Fairplay:view

app_contact_list:
    path: /liste-contact
    defaults:
        _controller: AppBundle:ContactList:listContact

app_place_list:
    path: /liste-gymnase
    defaults:
        _controller: AppBundle:PlaceList:listPlace
