app_index:
    path:     /
    defaults:
        _controller: AppBundle:Default:index

team_view:
    path: /team/{slug}
    defaults:
        _controller: AppBundle:Team:view

history_view:
    path: /history
    defaults:
        _controller: AppBundle:History:view

fairplay_view:
    path: /fairplays
    defaults:
        _controller: AppBundle:Fairplay:view
