<?php

namespace InfoBundle\Repository;

/**
 * EditoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EditoRepository extends \Doctrine\ORM\EntityRepository
{
}
