<?php

namespace InfoBundle\Repository;

/**
 * FairPlayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FairPlayRepository extends \Doctrine\ORM\EntityRepository
{
}
