training_index:
    path:     /
    defaults:
        _controller: PlanningBundle:Training:index

training_show:
    path:     /{id}/show
    defaults:
        _controller: PlanningBundle:Training:show
    requirements:
        id: \d+

training_new:
    path:     /new
    defaults:
        _controller: PlanningBundle:Training:new

training_edit:
    path:     /{id}/edit
    defaults:
        _controller: PlanningBundle:Training:edit
    requirements:
            id: \d+

training_delete:
    path:     /{id}/delete
    defaults:
        _controller: PlanningBundle:Training:delete
    requirements:
            id: \d+