admin_place_index:
    path:     /
    defaults:
        _controller: PlaceBundle:Place:index

admin_place_show:
    path:     /{id}/show
    defaults:
        _controller: PlaceBundle:Place:show
    requirements:
        id: \d+

admin_place_new:
    path:     /new
    defaults:
        _controller: PlaceBundle:Place:new

admin_place_edit:
    path:     /{id}/edit
    defaults:
        _controller: PlaceBundle:Place:edit
    requirements:
            id: \d+

admin_place_delete:
    path:     /{id}/delete
    defaults:
        _controller: PlaceBundle:Place:delete
    requirements:
            id: \d+