info_history:
    resource: "@InfoBundle/Resources/config/routing/history.yml"
    prefix:   /history

info_homepage:
    path:     /
    defaults: { _controller: InfoBundle:Default:index }

info_fairplay:
    resource: "@InfoBundle/Resources/config/routing/fairplay.yml"
    prefix:   /fairplay
