event_index:
    path:     /
    defaults:
        _controller: EventBundle:Post:index

event_show:
    path:     /{id}/show
    defaults:
        _controller: EventBundle:Post:show
    requirements:
        id: \d+

event_new:
    path:     /new
    defaults:
        _controller: EventBundle:Post:new

event_edit:
    path:     /{id}/edit
    defaults:
        _controller: EventBundle:Post:edit
    requirements:
            id: \d+

event_delete:
    path:     /{id}/delete
    defaults:
        _controller: EventBundle:Post:delete
    requirements:
            id: \d+