post_index:
    path:     /
    defaults:
        _controller: EventBundle:Post:index

post_show:
    path:     /{id}/show
    defaults:
        _controller: EventBundle:Post:show
    requirements:
        id: \d+

post_new:
    path:     /new
    defaults:
        _controller: EventBundle:Post:new

post_edit:
    path:     /{id}/edit
    defaults:
        _controller: EventBundle:Post:edit
    requirements:
            id: \d+

post_delete:
    path:     /{id}/delete
    defaults:
        _controller: EventBundle:Post:delete
    requirements:
            id: \d+